# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = var.aws_region
  shared_credentials_file = "/Users/abriz/.aws/credentials"
  profile = "terra"
}
variable "aws_region" {
  default  = "ap-southeast-1"
}
terraform {
  backend "s3" {
  }
}
